[DEFAULT]

[Preprocess]
input_dir = ../../synergy_v2
output_dir = ./testing_preprocess
train_split_file = ['ONEIL_split_0_train.txt']
val_split_file = ['ONEIL_split_0_val.txt']
test_split_file = ['ONEIL_split_0_test.txt']
#data_format = .pkl
y_col_name = loewe
cell_transcriptomic_file = cell_transcriptomics.tsv
cell_transcriptomic_transform = [['subset', 'L1000_ENTREZ']]
drug_smiles_file = drug_smiles.tsv



[Train]
input_dir = ./testing_preprocess
output_dir = ./testing_train
model_file_format = .pt
learning_rate = 0.0005
epochs = 1000
#epochs = 2
batch_size = 256
val_batch = 256
patience = 100
data_format = .pkl
y_col_name = loewe
metric_type = classification

[Infer]
y_col_name = loewe
model_file_format = .pt
infer_batch = 256
calc_infer_scores = True
input_data_dir = ./testing_preprocess
input_model_dir = ./testing_train
output_dir = ./testing_infer
metric_type = classification
